# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dbt',
                'doc_host': 'https://nassersala.github.io',
                'git_url': 'https://github.com/nassersala/dbt',
                'lib_path': 'dbt'},
  'syms': { 'dbt.card': { 'dbt.card.Card': ('dbt.html#card', 'dbt/card.py'),
                          'dbt.card.Card.__eq__': ('dbt.html#card.__eq__', 'dbt/card.py'),
                          'dbt.card.Card.__init__': ('dbt.html#__init__', 'dbt/card.py'),
                          'dbt.card.Card.__lt__': ('dbt.html#card.__lt__', 'dbt/card.py'),
                          'dbt.card.Card.__str__': ('dbt.html#__str__', 'dbt/card.py'),
                          'dbt.card.foo': ('dbt.html#foo', 'dbt/card.py')},
            'dbt.core': {'dbt.core.foo': ('core.html#foo', 'dbt/core.py')},
            'dbt.dbt': { 'dbt.dbt.Card': ('dbt.html#card', 'dbt/dbt.py'),
                         'dbt.dbt.Card.__init__': ('dbt.html#__init__', 'dbt/dbt.py'),
                         'dbt.dbt.Card.__str__': ('dbt.html#__str__', 'dbt/dbt.py'),
                         'dbt.dbt.foo': ('dbt.html#foo', 'dbt/dbt.py')}}}