# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_dbt.ipynb.

# %% auto 0
__all__ = ['Card', 'foo']

# %% ../00_dbt.ipynb 8
class Card:
    "A playing card is created by passing self.suit to `suits` and self.rank to `ranks`"
    def __init__(self,
                 suit:int,  # An index into `suits`
                 rank:int): # An index into `ranks`
        self.suit,self.rank=suit,rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__ = __str__

# %% ../00_dbt.ipynb 13
@patch 
def __eq__(self:Card,a:Card): return (self.suit,self.rank)==(a.suit,a.rank)

# %% ../00_dbt.ipynb 15
00
@patch
def __lt__(self:Card,a:Card): return (self.suit,self.rank)<(a.suit,a.rank)

# %% ../00_dbt.ipynb 17
def foo(): pass
